version: "3"
services:
  jupyter:
    build: .
    image: jupyterlab:latest
    ports:
      - 8889:8889
    entrypoint: ["jupyter-lab","--port=8889","--ip=0.0.0.0","--no-browser","--allow-root","--NotebookApp.token=''"]

    volumes:
      - type: bind
        source: ./notebooks
        target: /project/notebooks
      - type: bind
        source: ./solutions
        target: /project/solutions